### ISSUE TITLE
Utilize sonobuoy progress

### ISSUE THREAD

**Issue by johnSchnake** [K8sbykeshed/k8s-service-validator#113]
While tests run (~10m I think, right?) we can use https://github.com/vmware-tanzu/sonobuoy-plugins/tree/main/plugin-helper to send updates as tests pass/fail. That way you can get faster feedback.

OK if I try and tackle this? It has a similar implementation as #102 since they both use the same helper library from Sonobuoy.

**Comment by yzaccc** [comment]
That's great! Thanks John for the info. Please go ahead to address this issue, would be awesome to see your commit! @johnSchnake
