### ISSUE TITLE
test session affinity loadbalancing

### ISSUE THREAD

**Issue by jayunit100** [K8sbykeshed/k8s-service-validator#34]
We should reproduce 
https://github.com/kubernetes/kubernetes/issues/103000

**Comment by yzaccc** [comment]
as currently the kind cluster for testing is using kube-proxy mode ipvs. Testify if the service affinity is per-client-per-port, or per-client-per-pod. 

Context:
per-client-per-port: a client connects to same service via different port, can be directed to different pods. Affiliation: port <-> pod.
per-client-per-pod: a client connects to same service via different port, always goes to the same pod. Affiliation: service <-> pod.
