### ISSUE TITLE
sonobuoy plugin

### ISSUE THREAD

**Issue by jayunit100** [K8sbykeshed/k8s-service-validator#58]
Make a sonobuoy plugin that bundles the service-lb-validator so that we can validate it for vmware-tanzu

**Comment by yzaccc** [comment]
sonobuoy plugins: https://github.com/vmware-tanzu/sonobuoy-plugins

**Comment by yzaccc** [comment]
solved in https://github.com/K8sbykeshed/k8s-service-validator/pull/80
