### ISSUE TITLE
Refine log and matrix

### ISSUE THREAD

**Issue by yzaccc** [K8sbykeshed/k8s-service-validator#60]
- include logs to know which node each pod got scheduled
- refine matrix to know which node each pod is running on
- colorize the std outputs
- tbd

**Comment by knabben** [comment]
- we can log the node in the beginning, there's no need to print in the matrix, because is too much information.
- omg https://github.com/fatih/color
- set verbosity via flags --debug or -v

**Comment by knabben** [comment]
lets try print colors in the matrix, green for . and red for x, maaaybe...

**Comment by knabben** [comment]
Fixed on https://github.com/K8sbykeshed/k8s-service-validator/pull/90
