### ISSUE TITLE
expected failure for sessionaffinity with different ports

### ISSUE THREAD

**Issue by knabben** [K8sbykeshed/k8s-service-validator#89]
We should refactor the test `"should always reach to same pod, even with via different protocol"`, so only session affinity across hosts are expected, not ports, since this is not implemented/guaranteed in any proxy.

For now skipping the test, so the CI can have the control job (kproxy iptables) passing.

@yzaccc

**Comment by yzaccc** [comment]
return "?" for the result of the test(not to fail the pipeline), as the test is expected to fail currently.
